name: TradePlus
version: 2.31
author: Trophonix
main: com.trophonix.tradeplus.TradePlus
commands:
  trade:
    description: Trade command
  tradeplus:
    description: TradePlus admin command
    permission: tradeplus.admin
permissions:
  tradeplus.admin:
    description: TradePlus admin permission
    default: op
    children:
      tradeplus.trade: true